name: subjective-abstract-data-source
channels:
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - pandas>=1.5.0
  - pip:
      - brainboost-data-source-logger-package @ git+ssh://git@github.com/PabloBorda/brainboost_data_source_logger_package.git
      - brainboost-configuration-package @ git+ssh://git@github.com/PabloBorda/brainboost_configuration_package.git
      - alive-progress>=3.1.5
